name: Mirror to CodeCommit

on:
  push:

jobs:
  mirror_to_codecommit_prod:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          ssh://git-codecommit.ca-central-1.amazonaws.com/v1/repos/cdk-constructs
        ssh_private_key:
          ${{ secrets.PROD_CODECOMMIT_SSH_PRIVATE_KEY }}
        ssh_username:
          ${{ secrets.PROD_CODECOMMIT_SSH_PRIVATE_KEY_ID }}
